export const pokemonConstants = {
    POKEMON_GET: 'POKEMON_GET',
    POKEMON_GET_SUCCESS: 'POKEMON_GET_SUCCESS',
    POKEMON_GET_FAILURE: 'POKEMON_GET_FAILURE',

    POKEMON_POST: 'POKEMON_POST',
    POKEMON_POST_SUCCESS: 'POKEMON_POST_SUCCESS',
    POKEMON_POST_FAILURE: 'POKEMON_POST_FAILURE',

    POKEMON_DELETE: 'POKEMON_DELETE',
    POKEMON_DELETE_SUCCESS: 'POKEMON_DELETE_SUCCESS',
    POKEMON_DELETE_FAILURE: 'POKEMON_DELETE_FAILURE',

    FAVOURITE_ADD: 'FAVOURITE_ADD'
};